name: compile

on: 
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: Compile
    cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
            ./pio
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install
        run: | 
            pip install --upgrade platformio
            pio pkg install -g -t platformio/tool-mkspiffs
      - name: compile
        run: |
            pio run
      - name: buildfs
        run: |
            pio run --target buildfs
      - name: copy
        run: |
            cd .pio/build
            rm ../../docs/programmer/firmware/configurations_info.txt
            for folder in $(ls -td -- */|tac); do
            if [ -d "$folder" ]; then
                mkdir -p ../../docs/programmer/firmware/$folder
                cp -rf $folder/firmware.bin ../../docs/programmer/firmware/$folder/firmware.bin
                cp -rf $folder/littlefs.bin ../../docs/programmer/firmware/$folder/littlefs.bin
                cp -rf $folder/partitions.bin ../../docs/programmer/firmware/$folder/partitions.bin
                cp -rf $folder/bootloader.bin ../../docs/programmer/firmware/$folder/bootloader.bin
                cp -rf ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin ../../docs/programmer/firmware/$folder/boot_app0.bin
                echo "$folder" >> ../../docs/programmer/firmware/configurations_info.txt
            fi
            done
      - name: git push
        run: |
            git config user.name "robot-control-modules"
            git config user.email "166165902+robot-control-modules@users.noreply.github.com"
            git config advice.addIgnoredFile false
            git add .
            git commit -m "[bot] compiled firmware"
            git push
