name: compile

on: 
    push:
    workflow_dispatch:

concurrency:
    group: Compile
    cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: build
        run: | 
            pip install --upgrade platformio
            pio pkg install -g -t platformio/tool-mkspiffs
            pio run
            pio run --target buildfs
            cd .pio/build
            for folder in ./*; do
            if [ -d "$folder" ]; then
                mkdir ../../docs/programmer/$folder
                cp -rf $folder/firmware.bin ../../docs/programmer/$folder/firmware.bin
                cp -rf $folder/littlefs.bin ../../docs/programmer/$folder/littlefs.bin
            fi
            done
            git config user.name "joshua-8[bot]"
            git config user.email "joshua-8@users.noreply.github.com"
            git add .
            git commit -m "compiled firmware"
            git push
