name: compile

on: 
    push:
    workflow_dispatch:

concurrency:
    group: Compile
    cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: build
        run: | 
            echo "hi" > hi.txt
            git config user.name "joshua-8[bot]"
            git config user.email "59814881+joshua-8@users.noreply.github.com"
            git config advice.addIgnoredFile false
            git add .
            git commit -m "compiled firmware"
            git push
